### ISSUE TITLE
Uncaught Twig\Error\SyntaxError: Unknown "template_from_string" function

### ISSUE THREAD

**Issue by chrisvidal** [cearls/timberland#10]
`{{ include(template_from_string(copyright)) }}` or `{% include template_from_string(copyright) %}`, from Timber documentation, results in the following error: 

```
Uncaught Twig\Error\SyntaxError: Unknown "template_from_string" function
```

not sure if this is because of the theme, I would expect that a code from Timber doc. would work.

**Comment by Stickyeyes-Vohra** [comment]
Did you ever figure out why it wasn't working? Im getting the same error.
