### ISSUE TITLE
Tailwind 3.0

### ISSUE THREAD

**Issue by TheR3mi** [cearls/timberland#12]
Is it possible for you to update to tailwind 3.0 ?

Thanks for your work!

**Comment by cearls** [comment]
Yes, I will be upgrading to Tailwind 3.0 soon!

**Comment by cearls** [comment]
There is now a v1 release of this theme with Tailwind 3.0. However, this release introduces a big change where editing pages now uses the WP block editor and visual editing. Keep that in mind if you were expecting it work like previous versions.

If you need to upgrade an existing project, following the Tailwind upgrade guide was pretty quick.

[https://tailwindcss.com/docs/upgrade-guide](https://tailwindcss.com/docs/upgrade-guide)

**Comment by TheR3mi** [comment]
So cool !

It's not a problem because I started a new project not long ago so I will restart with the V1.

Nice work thanks !
