### ISSUE TITLE
Unexpected token s in JSON at position 2

### ISSUE THREAD

**Issue by bdfpplinsinga** [cearls/timberland#13]
Question, im wondering how you work with alphine js inside the editor? When i use it on alway getting a error on a block that uses alphine js. 

It seems im getting a json error on the x-data="{ }" part. Dont you have this, or is there a workaround that you implemented?

**Comment by cearls** [comment]
Hi! Alpine code should work in the visual editor. Can you provide code that I can test?

**Comment by cearls** [comment]
I'm closing this issue. Please re-open if you'd like me to look into this more.
