### ISSUE TITLE
[Question] Add scss support

### ISSUE THREAD

**Issue by RichForever** [cearls/timberland#14]
Hi, are you planning to add scss support for custom styles? I mean any compiler or something? I’m using gulp for this in another theme and I want to switch to your theme but this is the thing that missing.

**Comment by cearls** [comment]
Hi! The theme uses Laravel Mix, which supports Sass. It should take minimal updates to your webpack.mix.js file. I've linked to the documentation below.

https://laravel-mix.com/docs/main/sass

**Comment by RichForever** [comment]
Sweet! I’ll take a look. Thanks

**Comment by cearls** [comment]
That's good to hear. I'm glad you got it working!
