### ISSUE TITLE
[Bug] Creating new blocks adding .DS_Store block on MacOS

### ISSUE THREAD

**Issue by RichForever** [cearls/timberland#15]
Hi, I tried to create new example block. Simply copy existing directory, change name and html structure in the twig file. When I done that and go to the Gutenberg editor I see 3 blocks. One of them is .DS_Store. I checked my theme directories and there's no such file. So my question is how to get rid ot that block and what can I do in the future to avoid that situation? I'm working on mac os system.

<img width="333" alt="Zrzut ekranu 2022-05-24 o 19 57 05" src="https://user-images.githubusercontent.com/11215070/170101756-103af4b2-6a8e-4f13-b1d1-db26e016a3d0.png">

**Comment by cearls** [comment]
Hi, .DS_Store files are automatically created by macOS when using Finder and are hidden by default. You can use **command + shift + .** to view and delete them.

**Comment by RichForever** [comment]
Yes, I know that but the thing is that there's no such a file 
<img width="343" alt="Zrzut ekranu 2022-05-25 o 09 20 44" src="https://user-images.githubusercontent.com/11215070/170204193-1a7bffdd-c2c2-4a96-953c-2ed051243006.png">

<img width="222" alt="Zrzut ekranu 2022-05-25 o 09 20 06" src="https://user-images.githubusercontent.com/11215070/170204218-5bcc1f25-2571-49d5-a15b-e5e357dea2f8.png">

**Comment by RichForever** [comment]
Yeah, thats weird. Anyway, I was able to delete all .DS_Store files with command line and now everything is ok.
