### ISSUE TITLE
question: component based javascript files

### ISSUE THREAD

**Issue by kilianso** [cearls/timberland#16]
Hey there, cool repo! I think this could be a great successor of something like Flynt.

However, i was wondering how you instantiate script files in a component if you have two or more of the same blocks on the same page. If you use Alpine directly as attributes within the twig files, that shouldn't be an issue since Alpine will take care of it afaik. But let's say you have a component that uses some classic `document.querySelector` stuff in a `script.js` file. What's going on in this case? Will you just bundle everything in a single file or is there some unseen logic that creates instances or even web components like Flynt does?

Cheers

PS: Maybe it would be better to have the discussion tab activated for questions like this.

**Comment by cearls** [comment]
Hey! Flynt is great and was part of the inspiration for this project.

I've mostly used Alpine directly as attributes, which has worked great. Everything is bundled into one file. You could use a combination of Alpine's `x-init` and `x-ref` to reference an element inside a script.js function. The article below shows a good example of this.

[https://carouth.com/articles/flexible-carousel-with-alpinejs/](https://carouth.com/articles/flexible-carousel-with-alpinejs/)

[https://alpinejs.dev/directives/init](https://alpinejs.dev/directives/init)
[https://alpinejs.dev/directives/ref](https://alpinejs.dev/directives/ref)

Thanks for the discussion tab suggestion. I've enabled it.
