### ISSUE TITLE
How to deploy theme to the production server?

### ISSUE THREAD

**Issue by RichForever** [cearls/timberland#18]
Hi, I'm trying to deploy the theme to the public server on the final website. I think there's some things that is missing or I'am doing it wrong.

1. What files should be deployed to the server?
With the normal theme it will be just `theme_folder` inside `wp-content/themes`. How about this? Which directories should I deploy? `vendor` and `theme`?

2. What's the purpose of the `build` directory?
For me, this is the final files (minifed etc) for the production site. There should be all font files, images, styles and scripts since I don't want to share any css/scss/js soruce files. Am I right? If yes, there's missing configuration inside mix file regarding images and fonts. When I run `npm production` inside `assets/buld` there's no images or fonts. They are in the `assets` directory. So, my question is which files should be in the `assets/build` directory and which one in the `assets`

3. Is it possible to use the theme with plugin instead of vendor version?

**Comment by cearls** [comment]
Hi! It sounds like you're on the right track. I've recently been thinking about the best ways to deploy to production myself.

1. You deploy the theme and vendor directories in a parent theme directory. You should have `wp-content/themes/timberland/theme` and `wp-content/themes/timberland/vendor`.
2. I use the `assets/build` directory for the bundled css and js files. I reference fonts and images in the `assets` directory. You could remove the `assets/styles` and `assets/scripts` directories from production if you'd like.
3. You can use Timber as a plugin, but version 2 will not have plugin support. I'm not sure when that will happen, but I will upgrade the theme at some point after it releases.
[https://timber.github.io/docs/v2/upgrade-guides/2.0/#no-more-plugin-support](https://timber.github.io/docs/v2/upgrade-guides/2.0/#no-more-plugin-support)

**Comment by RichForever** [comment]
@cearls thank you for clarification. I can't wait for Timber and Timberland updates! Cheers
