### ISSUE TITLE
Can't active theme on the Windows machine

### ISSUE THREAD

**Issue by RichForever** [cearls/timberland#20]
Hi,
I'm trying to open up my project built on the macos machine in the windows based machine. I have clean wordpress installation. I cloned this repo, install all  dependencies via composer and npm. Then I run npm build tasks. When I'm trying to open the website I have error message

`Fatal error: Uncaught Exception: The Mix manifest does not exist. in C:\MAMP\htdocs\xxx\wp-content\themes\xxx\theme\functions.php:200 Stack trace: #0 C:\MAMP\htdocs\xxx\wp-content\themes\xxx\theme\functions.php(101): Timberland->mix('/app.css', '/C:\\MAMP\\htdocs...') #1 C:\MAMP\htdocs\xxx\wp-includes\class-wp-hook.php(307): Timberland->enqueue_scripts('') #2 C:\MAMP\htdocs\xxx\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #3 C:\MAMP\htdocs\xxx\wp-includes\plugin.php(476): WP_Hook->do_action(Array) #4 C:\MAMP\htdocs\xxx\wp-includes\script-loader.php(2156): do_action('wp_enqueue_scri...') #5 C:\MAMP\htdocs\xxx\wp-includes\class-wp-hook.php(307): wp_enqueue_scripts('') #6 C:\MAMP\htdocs\xxx\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #7 C:\MAMP\htdocs\xxx\wp-includes\plugin.php(476): WP_Hook->do_action(Array) #8 C:\MAMP\htdocs\xxx\wp-includes\general-template.php(3042): do_action('wp_head in C:\MAMP\htdocs\xxx\wp-content\themes\xxx\theme\views\base.twig on line 10`

I'm working with MAMP and with Local by Flywheel but I have the same error in both of these environments. In fact, the manifest file is present in the `theme\assets\build` directory. So, my question is how to get it work :)

**Comment by RichForever** [comment]
It looks like this lines generates the errors

functions.php, line 194

`if ($manifestDirectory && strpos($manifestDirectory, '/') !== 0) {
    $manifestDirectory = "/{$manifestDirectory}";
}`

**Comment by zync09** [comment]
I couldn't get this to run either. I posted a thread earlier in Oct 21 with the same issue but finally managed to fix it today.

Reason is, var_dump of $manifestPath for me gives:
string(78) "C:\laragon\www\playground/wp-content/themes/timberland-main/theme/assets/build"

if I don't comment out that code it dumps as:
string(79) "/C:\laragon\www\playground/wp-content/themes/timberland-main/theme/assets/build"

That bit of code seems to add a / in front of that and it messes things up.

Fix on left, old code on right.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/4277442/198437031-81b4083d-a967-4aa3-882f-baee626ae7a5.png">

**Comment by cearls** [comment]
Thanks for the pull request @zync09  🎉. I've merged it and put out a release.
