### ISSUE TITLE
How to create child theme?

### ISSUE THREAD

**Issue by RichForever** [cearls/timberland#32]
Hi, I'm wondering is there any way to create child theme in current approach where theme files are located in the "theme" subdirectory?
I tried to create timberland-child directory. Inside it I made "theme" directory which contain style.css file. When I go to the wordpress panel I can see message that says "the parent theme is missing. please install the parent theme".

So what should I do? Ommit the "theme" subdir and move all files to main directory?

**Comment by cearls** [comment]
Hi, I've never used Timberland as a child theme because of how much custom code is required to use it on a project. It's a starter theme vs. a traditional theme where you might use the customizer. What's the use case?

**Comment by RichForever** [comment]
I’m making my starter theme that I’ll use to build websites for my clients. To be honest i already have that theme. I want to create child theme that will be used by my clients.
