### ISSUE TITLE
Shouldn't this also be included in the other styles?

### ISSUE THREAD

**Issue by bdfpplinsinga** [cearls/timberland#33]
https://github.com/cearls/timberland/blob/75614619b471274ce2233163a0112da2c57c3b62/theme/functions.php#L135

**Comment by cearls** [comment]
You could use this font in the editor if you want. I'm usually using other fonts in my site styles and they are included on the front-end and in the editor.

**Comment by cearls** [comment]
Actually, after checking a current project, I'm only loading site fonts on the front-end and getting fallback fonts in the editor. You could use this to load your site fonts in the editor and make it reflect the front-end better.
