### ISSUE TITLE
vite.config.js documentation

### ISSUE THREAD

**Issue by bdfpplinsinga** [cearls/timberland#39]
Hi Chris,

Quick question. Im using your new setup with vite and it looks really good. I have only a small thing. I cant seem to get the vite config right. What do i need to change to get this live reload working? 

I tried to change the host but no luck with that. Im i missing something?

**Comment by bdfpplinsinga** [comment]
Nevermind. Just had to add :

```javascript
liveReload: true,
```

**Comment by bdfpplinsinga** [comment]
Nevermind. Just had to add :

```javascript
liveReload: true,
```

**Comment by cearls** [comment]
Hey! Live reload should be working by default in development. It's controlled by the vite environment parameter in the config.json file.

https://github.com/cearls/timberland/blob/main/config.json

Live reload will be disabled if the config.json file doesn't exist, which is how I run the theme on a production site (only theme and vendor directories), or the environment is set to production.

**Comment by bdfpplinsinga** [comment]
Hee Chris,

In my setup this doesn't seem to work. Maybe this has anything to do with the fact that I'm using 'normal' urls instead of localhost. So by default it's opening localhost:3000 when running npm run dev. But this gives back a dns error.
