### ISSUE TITLE
WordPress 6.6 Link Styling Bug

### ISSUE THREAD

**Issue by cearls** [cearls/timberland#43]
**Issue:** WordPress 6.6 enqueues new global styles that cause all links to be underlined.

**Solution:** Add the following line to the [enqueue_assets function in functions.php](https://github.com/cearls/timberland/blob/4342920981d09c1e3b90785899092569b9db4424/theme/functions.php#L60):

`wp_dequeue_style('global-styles');`

**Note:** This issue is expected to be fixed in WordPress 6.6.1. However, include this fix in the theme to be safe.

**Comment by ineptian** [comment]
In case anyone comes back to this, this is now needed to prevent the global styles bug: 
`remove_action( 'wp_footer', 'wp_enqueue_global_styles', 1 );`

You can add it directly beneath `wp_dequeue_style( 'global-styles' );` in your `functions.php`.
